### ISSUE TITLE
Focus escapes to Chrome title bar

### ISSUE THREAD

**Issue by erikjalevik** [henrygd/trap-focus-svelte#5]
I can't really get this library to work. When testing in Chrome, and I tab out of the modal on which it was added, focus moves to the currently active Chrome tab at the top of the window. When this happens, no `focusin` event seems to be delivered.

Furthermore, if I keep tabbing, the focus eventually comes back to the actual web page content again, `focusin` does get delivered, but the focus still doesn't end up back in the modal. I can see that the code issues the `firstFocusable.focus()` call but it tries to set it on an element in the dialog that isn't actually focusable, and the focus remains on the first link in the content below the modal.

**Comment by henrygd** [comment]
Thanks, is the issue also present for you on the [demo page](https://trap-focus-svelte.henrygd.me/)?

If not, can you please provide a minimal reproduction in a repo, stackblitz, or codesandbox?

**Comment by erikjalevik** [comment]
Hmm, strange, in the demo page the focus stays trapped. Even with the modal closed, focus does not travel to Chrome's UI elements outside the page. Open any other site though, like www.google.com and start hitting Tab and you'll eventually end up in the tab bar.

I actually abandoned this lib and implemented my own action based on the approach used in https://github.com/ghosh/Micromodal instead (catching all Tab key presses instead of relying on focus events), which seems to work better for our use case. So I don't have a repro I'm afraid.

**Comment by henrygd** [comment]
Okay, no worries
